<?xml version="1.0" encoding="utf-8"?><Database Name="Dessert Shop" Class="Order_managementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Alice\MSSQLSERVER01;Initial Catalog=&quot;Dessert Shop&quot;;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Dessertshop.Properties.Settings" SettingsPropertyName="Dessert_ShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OrderDetail" Member="OrderDetail">
    <Type Name="OrderDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Order_number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Order_Item" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OrderList" Member="OrderList">
    <Type Name="OrderList">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ShipDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Product">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Unitprice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pimage" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customer">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Limits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>